AcceptionRatio;
MigrationFrequence;

UtilizationCurrentVirtualNewtork;
UtilizationAccumulateVirtualNewtork;
UtilizationCurrentSubstrateNewtork;
UtilizationAccumulateSubstrateNewtork;

StressCurrentVirtualNewtork;
StressAccumulateVirtualNewtork;
StressCurrentSubstrateNewtork;
StressAccumulateSubstrateNewtork;


CostCurrentSubstrateNewtork;
CostAccumulateSubstrateNewtork;
 CostAverageCurrentSubstrateNewtork;
CostAverageAccumulateSubstrateNewtork;


RevenueCurrentVirtualNewtork;
RevenueAverageCurrentVirtualNewtork;
RevenueAccumulateVirtualNewtork;
RevenueAverageAccumulateVirtualNewtork;



UtilizationSubVir2VirNet;
UtilizationSubVir2VirNetAccumulate;


CostRevenue;
CostRevenueAccumulate;

VirNetReqSurNetReq;


